from battle import minion, battlefeild, battle

def simple_test0():#啥都没有，基础检测
    ba = battlefeild()
    return ba
def simple_test1():#只有上面，基础检测
    a = minion("Zapp Slywick", 6, 16, spe="Zapp Slywick", g=True)
    ba = battlefeild()
    ba.add_minion(a, "up", 0)
    return ba
def simple_test2():#只有下面，基础检测
    a = minion("Zapp Slywick", 6, 16, spe="Zapp Slywick", g=True)
    ba = battlefeild()
    ba.add_minion(a, "down", 0)
    return ba
def simple_test3():#简单对撞
    a = minion("Zapp Slywick", 6, 16, spe="Zapp Slywick", g=True)
    b = minion("Zapp Slywick", 6, 16, spe="Zapp Slywick")
    ba = battlefeild()
    ba.add_minion(a, "down", 0)
    ba.add_minion(b, "up", 0)
    return ba

def test1():#检测狂战，腐树，爆爆，老瞎眼
    a = minion("Foe Reaper 4000", 6, 16, spe="Foe Reaper 4000",g=True, ch="Mech")
    b = minion("Kaboom Bot", 6, 10, ch="Mech", ra="Kaboom Bot")
    c = minion("Kaboom Bot", 10, 11, ch="Mech", ra="Kaboom Bot")
    d = minion("Kaboom Bot", 6, 11, ch="Mech", ra="Kaboom Bot")
    e = minion("Kaboom Bot", 6, 16, ch="Mech", ra="Kaboom Bot")
    f = minion("Kaboom Bot", 7, 15, ch="Mech", ra="Kaboom Bot")
    g = minion("Kaboom Bot", 5, 12, sh=True, t=True,g=True, ch="Mech", ra="Kaboom Bot")
    h = minion("Old Murk-Eye", 22, 6, sh=True, g=True, ch="Murloc", spe="Old Murk-Eye")
    i = minion("Murloc Tidehunter", 12, 12, sh=True, ch="Murloc")
    j = minion("Murloc Tidehunter", 5, 12, sh=True, ch="Murloc")
    k = minion("Murloc Tidehunter", 6, 12, sh=True, ch="Murloc")
    l = minion("Festeroot Hulk", 8, 12, sh=True, spe="Festeroot Hulk")
    m = minion("Brann Bronzebeard", 4, 6, t=True)
    n = minion("Murloc Warleader", 5, 12, sh=True, p=True,ch="Murloc", spe="Murloc Warleader")
    ba = battlefeild()
    ba.add_minion(b, "up", 0)
    ba.add_minion(a, "up", 1)
    ba.add_minion(c, "up", 2)
    ba.add_minion(d, "up", 3)
    ba.add_minion(e, "up", 4)
    ba.add_minion(f, "up", 5)
    ba.add_minion(g, "up", 6)
    ba.add_minion(h, "down", 0)
    ba.add_minion(i, "down", 1)
    ba.add_minion(j, "down", 2)
    ba.add_minion(k, "down", 3)
    ba.add_minion(l, "down", 4)
    ba.add_minion(m, "down", 5)
    ba.add_minion(n, "down", 6)
    return ba

def test2():#检测buff和狂战
    a = minion("Foe Reaper 4000", 6, 16, spe="Foe Reaper 4000", g=True, ch="Mech")
    n = minion("Murloc Warleader", 12, 112,  ch="Murloc", spe="Murloc Warleader")
    ba = battlefeild()
    ba.add_minion(a, "up", 1)
    ba.add_minion(n, "down", 6)
    return ba

def test3():#检测生命buff刷新
    a = minion("Mal'Ganis", 16, 6, spe="Mal'Ganis",g=True, ch="Demon")
    b= minion("Nathrezim Overseer", 6, 16, t=True, ch="Demon")
    c=minion("Nathrezim Overseer", 3, 4, ch="Demon")
    d=minion("Nathrezim Overseer", 6, 16, ch="Demon")
    e = minion("Murloc Warleader", 12, 112, t=True, ch="Murloc", spe="Murloc Warleader")
    ba = battlefeild()
    ba.add_minion(a, "up", 0)
    ba.add_minion(b, "up", 1)
    ba.add_minion(c, "down", 0)
    ba.add_minion(d, "down", 1)
    ba.add_minion(e, "down", 2)
    return ba

def test4():#检测伯瓦尔，金爆爆
    a = minion("Foe Reaper 4000", 6, 16, spe="Foe Reaper 4000", g=True, ch="Mech")
    b = minion("Kaboom Bot", 6, 10, ch="Mech", ra="Kaboom Bot")
    c = minion("Kaboom Bot", 10, 11, ch="Mech", ra="Kaboom Bot")
    d = minion("Kaboom Bot", 6, 11, ch="Mech", ra="Kaboom Bot")
    e = minion("Kaboom Bot", 6, 16, ch="Mech", ra="Kaboom Bot")
    f = minion("Kaboom Bot", 7, 15, ch="Mech", g=True,ra="Kaboom Bot")
    g = minion("Kaboom Bot", 5, 12, sh=True, t=True, ch="Mech", ra="Kaboom Bot")
    h = minion("Old Murk-Eye", 22, 6, sh=True, g=True, ch="Murloc", spe="Old Murk-Eye")
    i =minion("Bolvar, Fireblood", 8, 12, sh=True, spe="Bolvar, Fireblood")
    j = minion("Murloc Tidehunter", 5, 12, sh=True, ch="Murloc")
    k = minion("Murloc Tidehunter", 6, 12, sh=True, ch="Murloc")
    l = minion("Murloc Tidehunter", 12, 12, sh=True, ch="Murloc")
    m = minion("Brann Bronzebeard", 4, 6, t=True)
    n = minion("Murloc Warleader", 5, 12, sh=True, ch="Murloc", spe="Murloc Warleader")
    ba = battlefeild()
    ba.add_minion(b, "up", 0)
    ba.add_minion(a, "up", 1)
    ba.add_minion(c, "up", 2)
    ba.add_minion(d, "up", 3)
    ba.add_minion(e, "up", 4)
    ba.add_minion(f, "up", 5)
    ba.add_minion(g, "up", 6)
    ba.add_minion(h, "down", 0)
    ba.add_minion(i, "down", 1)
    ba.add_minion(j, "down", 2)
    ba.add_minion(k, "down", 3)
    ba.add_minion(l, "down", 4)
    ba.add_minion(m, "down", 5)
    ba.add_minion(n, "down", 6)
    return ba

def test5():#检测金爆爆，伯瓦尔互动
    a=minion("Kaboom Bot", 6, 6, ch="Mech", g=True,ra="Kaboom Bot")
    b= minion("Murloc Tidehunter", 6, 6, ch="Murloc")
    c= minion("Murloc Tidehunter", 5, 4, sh=True, ch="Murloc")
    d =minion("Bolvar, Fireblood", 8, 12, sh=True, spe="Bolvar, Fireblood")
    ba = battlefeild()
    ba.add_minion(a, "up", 0)
    ba.add_minion(b, "down", 0)
    ba.add_minion(c, "down", 1)
    ba.add_minion(d, "down", 2)
    return ba

def test6():#检测零攻互动
    a=minion("Kaboom Bot", 4, 12, ch="Mech", g=True,sh=True,ra="Kaboom Bot")
    b= minion("Murloc Tidehunter", 0, 6, ch="Murloc")
    c= minion("Murloc Tidehunter", 0, 6, ch="Murloc")
    d =minion("Bolvar, Fireblood", 0, 12, sh=True, spe="Bolvar, Fireblood")
    e =minion("Bolvar, Fireblood", 0, 12, sh=True, spe="Bolvar, Fireblood")
    f= minion("Murloc Tidehunter", 0, 6, ch="Murloc")
    g = minion("Festeroot Hulk", 0, 12,  spe="Festeroot Hulk")
    ba = battlefeild()
    ba.add_minion(a, "up", 0)
    ba.add_minion(b, "down", 0)
    ba.add_minion(c, "down", 1)
    ba.add_minion(d, "down", 1)
    ba.add_minion(e,"down",3)
    ba.add_minion(f,"down",4)
    ba.add_minion(g,"down",5)
    return ba

def test7():#检测恐狼，土狼，喷子
    a = minion("Cave Hydra", 6, 10,ch="Beast",spe="Cave Hydra")
    b = minion("Dire Wolf Alpha", 6, 10, ch="Beast",spe="Dire Wolf Alpha")
    c = minion("Alleycat", 10, 11, ch="Beast")
    d = minion("Alleycat", 10, 11, ch="Beast")
    e = minion("Alleycat", 10, 11, ch="Beast")
    f = minion("Scavenging Hyena", 7, 15, ch="Beast",spe="Scavenging Hyena" )
    g = minion("Scavenging Hyena", 6, 16, spe="Scavenging Hyena", g=True, ch="Beast")
    h = minion("Vulgar Homunculus", 4, 6,t=True,ch="Demon")
    i =minion("Vulgar Homunculus", 8, 6,t=True,ch="Demon")
    j = minion("Vulgar Homunculus", 8, 6, t=True,ch="Demon")
    k = minion("Vulgar Homunculus", 4, 6,t=True,ch="Demon")
    l = minion("Mal'Ganis", 12, 12, ch="Demon",spe="Mal'Ganis")
    m = minion("Vulgar Homunculus", 4, 6, t=True,ch="Demon")
    n = minion("Soul Juggler", 5, 12, g=True,spe="Soul Juggler")
    ba = battlefeild()
    ba.add_minion(a, "up", 0)
    ba.add_minion(b, "up", 1)
    ba.add_minion(c, "up", 2)
    ba.add_minion(d, "up", 3)
    ba.add_minion(e, "up", 4)
    ba.add_minion(f, "up", 5)
    ba.add_minion(g, "up", 6)
    ba.add_minion(h, "down", 0)
    ba.add_minion(i, "down", 1)
    ba.add_minion(j, "down", 2)
    ba.add_minion(k, "down", 3)
    ba.add_minion(l, "down", 4)
    ba.add_minion(m, "down", 5)
    ba.add_minion(n, "down", 6)
    return ba

def test8():#检测狂战，安保
    a=minion("Cave Hydra", 6, 18, ch="Beast", g=True,spe="Cave Hydra")
    b =minion("Cobalt Guardian", 6, 3,ch="Mech",sh=True, spe="Cobalt Guardian")
    c =minion("Security Rover", 2, 6,ch="Mech", spe="Security Rover")
    d =minion("Security Rover", 2, 6,ch="Mech",t=True, spe="Security Rover")
    e =minion("Security Rover", 2, 6,ch="Mech", spe="Security Rover")
    ba = battlefeild()
    ba.add_minion(a, "up", 0)
    ba.add_minion(b, "down", 0)
    ba.add_minion(c, "down", 1)
    ba.add_minion(d, "down", 2)
    ba.add_minion(e, "down", 3)
    return ba

def test9():#检测卡德加，学徒，安保
    a = minion("Cave Hydra", 6, 18, ch="Beast", g=True, spe="Cave Hydra")
    b = minion("Cobalt Guardian", 6, 3, ch="Mech", spe="Cobalt Guardian")
    c = minion("Security Rover", 2, 6, ch="Mech", spe="Security Rover")
    d = minion("Security Rover", 2, 6, ch="Mech", t=True, spe="Security Rover")
    e = minion("Kangor's Apprentice", 3, 6, ra="Kangor's Apprentice")
    f = minion("Khadgar", 2, 2, g=True, spe="Khadgar")
    ba = battlefeild()
    ba.add_minion(a, "up", 0)
    ba.add_minion(b, "down", 0)
    ba.add_minion(d, "down", 1)
    ba.add_minion(c, "down", 2)
    ba.add_minion(e, "down", 3)
    ba.add_minion(f, "down", 4)
    return ba

def test10():#检测爆爆互动
    a = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    b = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    c = minion("Kaboom Bot", 10, 4, ch="Mech", ra="Kaboom Bot")
    d = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    e = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    f = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    g = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    h = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    i = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    j = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    k = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    l = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    m = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    n = minion("Kaboom Bot", 6, 4, ch="Mech",g=True, ra="Kaboom Bot")
    ba = battlefeild()
    ba.add_minion(b, "up", 0)
    ba.add_minion(a, "up", 1)
    ba.add_minion(c, "up", 2)
    ba.add_minion(d, "up", 3)
    ba.add_minion(e, "up", 4)
    ba.add_minion(f, "up", 5)
    ba.add_minion(g, "up", 6)
    ba.add_minion(h, "down", 0)
    ba.add_minion(i, "down", 1)
    ba.add_minion(j, "down", 2)
    ba.add_minion(k, "down", 3)
    ba.add_minion(l, "down", 4)
    ba.add_minion(m, "down", 5)
    ba.add_minion(n, "down", 6)
    return ba

def test11():#检测爆爆亡语互动
    a = minion("Harvest Golem", 6, 4, ch="Mech", ra="Harvest Golem")
    b = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    ba = battlefeild()
    ba.add_minion(a, "up", 0)
    ba.add_minion(b, "down", 0)
    return ba

def test12():#检测爆爆亡语互动
    a = minion("Harvest Golem", 6, 4, ch="Mech", ra="Harvest Golem")
    b = minion("Harvest Golem", 6, 4, ch="Mech", ra="Harvest Golem")
    c =minion("Harvest Golem", 6, 4, ch="Mech", ra="Harvest Golem")
    d = minion("Harvest Golem", 6, 4, ch="Mech", ra="Harvest Golem")
    e = minion("Harvest Golem", 6, 4, ch="Mech", ra="Harvest Golem")
    f = minion("Harvest Golem", 6, 4, ch="Mech", ra="Harvest Golem")
    g = minion("Harvest Golem", 6, 4, ch="Mech", ra="Harvest Golem")
    h = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    i = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    j = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    k = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    l = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    m = minion("Kaboom Bot", 6, 4, ch="Mech", ra="Kaboom Bot")
    n = minion("Kaboom Bot", 6, 4, ch="Mech",g=True, ra="Kaboom Bot")
    ba = battlefeild()
    ba.add_minion(b, "up", 0)
    ba.add_minion(a, "up", 1)
    ba.add_minion(c, "up", 2)
    ba.add_minion(d, "up", 3)
    ba.add_minion(e, "up", 4)
    ba.add_minion(f, "up", 5)
    ba.add_minion(g, "up", 6)
    ba.add_minion(h, "down", 0)
    ba.add_minion(i, "down", 1)
    ba.add_minion(j, "down", 2)
    ba.add_minion(k, "down", 3)
    ba.add_minion(l, "down", 4)
    ba.add_minion(m, "down", 5)
    ba.add_minion(n, "down", 6)
    return ba

def test13():#检测卡德加，野兽，小妈/熊妈
    a = minion("Cave Hydra", 6, 18, ch="Beast", g=True, spe="Cave Hydra")
    b = minion("Kindly Grandmother", 6, 3, ch="Beast", ra="Kindly Grandmother")
    c = minion("Pack Leader", 3, 3, spe="Pack Leader")
    d =  minion("Khadgar", 2, 2,  spe="Khadgar")
    e = minion("Khadgar", 2, 2,  spe="Khadgar")
    ba = battlefeild()
    ba.add_minion(a, "up", 0)
    ba.add_minion(b, "down", 0)
    ba.add_minion(c, "down", 1)
    ba.add_minion(d, "down", 2)
    ba.add_minion(e, "down", 3)
    return ba

